In [ ]:
import pandas as pd
df=pd.read_csv('premier_league_players_5years_with_rating.csv')
df.sample(2)

,player_name,team,opponent_team,season,match_number,minutes_played,goals,assists,shots,passes_completed,tackles,rating
10398,Conor Gallagher,Chelsea,Tottenham,2022,25,83,0,0,0,73,1,6.20
3306,Gabriel Jesus,Arsenal,Manchester City,2021,1,76,0,1,2,65,4,7.23

In [ ]:
df=df.drop(columns={'match_number','season' })

In [ ]:
df.sample(2)

,player_name,team,opponent_team,minutes_played,goals,assists,shots,passes_completed,tackles,rating
12993,Andre Onana,Manchester United,Arsenal,65,0,0,5,22,0,6.29
2699,Manuel Akanji,Manchester City,Tottenham,75,0,0,3,29,3,6.36

In [ ]:
df_encoded = pd.get_dummies(df,columns=["player_name","team","opponent_team"],dtype=int)

In [ ]:
df['player_name'].nunique()

90

In [ ]:
df.head(5)

,player_name,team,opponent_team,minutes_played,goals,assists,shots,passes_completed,tackles,rating
0,Erling Haaland,Manchester City,Manchester United,88,0,0,4,38,2,6.38
1,Erling Haaland,Manchester City,Tottenham,61,0,1,3,35,0,7.02
2,Erling Haaland,Manchester City,Manchester United,85,0,0,0,73,1,6.20
3,Erling Haaland,Manchester City,Manchester United,87,0,0,5,65,3,6.53
4,Erling Haaland,Manchester City,Manchester United,84,0,0,4,53,1,6.36

In [ ]:
df_encoded.head(5)

,minutes_played,goals,assists,shots,passes_completed,tackles,rating,player_name_Aaron Ramsdale,player_name_Alejandro Garnacho,player_name_Alexis Mac Allister,...,team_Liverpool,team_Manchester City,team_Manchester United,team_Tottenham,opponent_team_Arsenal,opponent_team_Chelsea,opponent_team_Liverpool,opponent_team_Manchester City,opponent_team_Manchester United,opponent_team_Tottenham
0,88,0,0,4,38,2,6.38,0,0,0,...,0,1,0,0,0,0,0,0,1,0
1,61,0,1,3,35,0,7.02,0,0,0,...,0,1,0,0,0,0,0,0,0,1
2,85,0,0,0,73,1,6.20,0,0,0,...,0,1,0,0,0,0,0,0,1,0
3,87,0,0,5,65,3,6.53,0,0,0,...,0,1,0,0,0,0,0,0,1,0
4,84,0,0,4,53,1,6.36,0,0,0,...,0,1,0,0,0,0,0,0,1,0

In [ ]:
y=df_encoded['rating']
X=df_encoded.drop(columns={'rating'})

In [ ]:
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

model = Sequential()

model.add(Dense(128, activation="relu", input_shape=(X.shape[1],)))
model.add(Dense(64, activation="relu"))
model.add(Dense(32, activation="relu"))

model.add(Dense(1))  # rating prediction

model.compile(
    optimizer="adam",
    loss="mse",
    metrics=["mae"]
)

model.fit(X, y, epochs=30, batch_size=64)

/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/dense.py:93: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

Epoch 1/30
268/268 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - loss: 5.9723 - mae: 1.5179
Epoch 2/30
268/268 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - loss: 0.4698 - mae: 0.5607
Epoch 3/30
268/268 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 0.2537 - mae: 0.4196
Epoch 4/30
268/268 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 0.1567 - mae: 0.3256
Epoch 5/30
268/268 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 0.0612 - mae: 0.2033
Epoch 6/30
268/268 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 0.0141 - mae: 0.0944
Epoch 7/30
268/268 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 0.0040 - mae: 0.0450
Epoch 8/30
268/268 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 0.0016 - mae: 0.0269
Epoch 9/30
268/268 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 0.0018 - mae: 0.0279
Epoch 10/30
268/268 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 0.0021 - mae: 0.0308
Epoch 11/30
268/268 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 0.0017 - mae: 0.0268
Epoch 12/30
268/268 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 0.0027 - mae: 0.0379
Epoch 13/30
268/268 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 0.0026 - mae: 0.0348
Epoch 14/30
268/268 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 0.0049 - mae: 0.0550
Epoch 15/30
268/268 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 0.0065 - mae: 0.0613
Epoch 16/30
268/268 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 0.0046 - mae: 0.0471
Epoch 17/30
268/268 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 0.0087 - mae: 0.0708
Epoch 18/30
268/268 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 0.0044 - mae: 0.0488
Epoch 19/30
268/268 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 0.0067 - mae: 0.0589
Epoch 20/30
268/268 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 0.0119 - mae: 0.0823
Epoch 21/30
268/268 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 0.0050 - mae: 0.0577
Epoch 22/30
268/268 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 0.0063 - mae: 0.0574
Epoch 23/30
268/268 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 0.0018 - mae: 0.0306
Epoch 24/30
268/268 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 0.0027 - mae: 0.0386
Epoch 25/30
268/268 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 0.0047 - mae: 0.0537
Epoch 26/30
268/268 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 0.0073 - mae: 0.0622
Epoch 27/30
268/268 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 0.0025 - mae: 0.0386
Epoch 28/30
268/268 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 0.0044 - mae: 0.0502
Epoch 29/30
268/268 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 0.0030 - mae: 0.0426
Epoch 30/30
268/268 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 0.0043 - mae: 0.0498

In [ ]:
print(model.predict(X[:2]))

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 119ms/step
[[6.347215]
 [6.991182]]

In [ ]:
y

0        6.38
1        7.02
2        6.20
3        6.53
4        6.36
         ...
17095    7.39
17096    7.15
17097    6.26
17098    6.28
17099    6.39
Name: rating, Length: 17100, dtype: float64

In [ ]:
y_predict=model.predict(X)

535/535 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step

In [ ]:
from sklearn.metrics import mean_squared_error
mse = mean_squared_error(y,y_predict)
mse

0.000718247808730584

In [ ]:
df_pt = df

In [ ]:
df_pt.head(1)

,player_name,team,opponent_team,minutes_played,goals,assists,shots,passes_completed,tackles,rating
0,Erling Haaland,Manchester City,Manchester United,88,0,0,4,38,2,6.38

In [ ]:
df_pt = df_pt.groupby(['player_name','team','opponent_team']).mean(numeric_only=True).reset_index()

In [ ]:
df_pt.head(2)

,player_name,team,opponent_team,minutes_played,goals,assists,shots,passes_completed,tackles,rating
0,Aaron Ramsdale,Arsenal,Chelsea,71.903226,0.193548,0.290323,2.838710,41.612903,2.000000,6.789032
1,Aaron Ramsdale,Arsenal,Liverpool,76.086957,0.391304,0.043478,2.782609,47.369565,2.217391,6.848696

In [ ]:
y_actual_pt =df_pt['rating']

In [ ]:
df_pt_encoded=pd.get_dummies(df_pt,columns=["player_name","team","opponent_team"],dtype=int)
df_pt_encoded=df_pt_encoded.drop(columns='rating')
df_pt_encoded

,minutes_played,goals,assists,shots,passes_completed,tackles,player_name_Aaron Ramsdale,player_name_Alejandro Garnacho,player_name_Alexis Mac Allister,player_name_Alisson Becker,...,team_Liverpool,team_Manchester City,team_Manchester United,team_Tottenham,opponent_team_Arsenal,opponent_team_Chelsea,opponent_team_Liverpool,opponent_team_Manchester City,opponent_team_Manchester United,opponent_team_Tottenham
0,71.903226,0.193548,0.290323,2.838710,41.612903,2.000000,1,0,0,0,...,0,0,0,0,0,1,0,0,0,0
1,76.086957,0.391304,0.043478,2.782609,47.369565,2.217391,1,0,0,0,...,0,0,0,0,0,0,1,0,0,0
2,76.111111,0.111111,0.177778,2.644444,47.288889,1.977778,1,0,0,0,...,0,0,0,0,0,0,0,1,0,0
3,73.000000,0.218750,0.156250,2.250000,46.093750,1.531250,1,0,0,0,...,0,0,0,0,0,0,0,0,1,0
4,74.583333,0.194444,0.166667,2.250000,43.527778,1.833333,1,0,0,0,...,0,0,0,0,0,0,0,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
445,77.935484,0.193548,0.290323,2.483871,48.838710,2.064516,0,0,0,0,...,0,0,0,1,1,0,0,0,0,0
446,76.236842,0.236842,0.236842,2.131579,45.631579,1.868421,0,0,0,0,...,0,0,0,1,0,1,0,0,0,0
447,75.857143,0.333333,0.214286,2.452381,46.642857,2.190476,0,0,0,0,...,0,0,0,1,0,0,1,0,0,0
448,73.777778,0.422222,0.200000,2.244444,45.977778,2.066667,0,0,0,0,...,0,0,0,1,0,0,0,1,0,0
449,74.882353,0.294118,0.264706,2.294118,46.176471,1.735294,0,0,0,0,...,0,0,0,1,0,0,0,0,1,0

In [ ]:
y_pt=model.predict(df_pt_encoded)
y_pt

15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step

array([[6.763661 ],
       [6.820114 ],
       [6.5726347],
       [6.6347737],
       [6.6258907],
       [6.913242 ],
       [6.7969694],
       [6.82586  ],
       [6.806486 ],
       [6.90312  ],
       [6.798142 ],
       [7.0222883],
       [6.998995 ],
       [6.86261  ],
       [6.6364093],
       [7.017465 ],
       [7.027671 ],
       [6.903692 ],
       [6.876598 ],
       [6.6756577],
       [6.8448305],
       [6.8109083],
       [7.0805655],
       [6.7734017],
       [6.493658 ],
       [6.9068956],
       [7.158973 ],
       [6.7420545],
       [6.724219 ],
       [6.7894278],
       [6.8514132],
       [6.86721  ],
       [6.9113936],
       [6.7865887],
       [6.9571185],
       [6.8550925],
       [6.846301 ],
       [6.8432236],
       [6.7386494],
       [6.754693 ],
       [7.328859 ],
       [7.0878296],
       [6.7813873],
       [6.7499166],
       [6.8800116],
       [6.818212 ],
       [6.8837957],
       [6.8617373],
       [6.9304566],
       [6.9606724],
       [6.8459225],
       [6.826968 ],
       [6.751365 ],
       [6.8697166],
       [6.8604636],
       [6.711148 ],
       [6.737035 ],
       [6.9536505],
       [6.705375 ],
       [6.7711153],
       [7.1306524],
       [6.9687595],
       [6.794422 ],
       [6.685896 ],
       [6.8167424],
       [6.7695794],
       [6.619995 ],
       [6.8340397],
       [6.773705 ],
       [6.786021 ],
       [7.0283785],
       [6.5489054],
       [6.828891 ],
       [6.974831 ],
       [6.7167892],
       [6.6027164],
       [6.814596 ],
       [6.8816504],
       [7.182607 ],
       [6.753326 ],
       [7.0527954],
       [6.6124287],
       [7.072763 ],
       [6.603717 ],
       [6.973654 ],
       [6.8449807],
       [6.769706 ],
       [6.763527 ],
       [6.792239 ],
       [6.866889 ],
       [6.8930745],
       [6.770641 ],
       [6.873005 ],
       [6.70263  ],
       [6.7978616],
       [6.7611213],
       [6.725394 ],
       [6.654656 ],
       [6.7683034],
       [6.921939 ],
       [6.80374  ],
       [6.738267 ],
       [6.8201036],
       [6.894844 ],
       [6.8817434],
       [6.755507 ],
       [6.686204 ],
       [6.643015 ],
       [6.7901897],
       [6.797239 ],
       [6.857522 ],
       [6.8619504],
       [6.59468  ],
       [6.700603 ],
       [6.8554664],
       [6.9838505],
       [6.992296 ],
       [6.6823807],
       [6.9993124],
       [6.9362264],
       [6.602947 ],
       [7.1500654],
       [7.2714396],
       [6.770339 ],
       [6.8649683],
       [6.808628 ],
       [6.8417215],
       [7.000346 ],
       [6.7828283],
       [7.009211 ],
       [6.76972  ],
       [6.677417 ],
       [6.720043 ],
       [6.918003 ],
       [6.5859103],
       [6.570657 ],
       [7.06772  ],
       [6.7436676],
       [6.817132 ],
       [6.6802855],
       [7.143226 ],
       [6.9829516],
       [6.760829 ],
       [6.9067674],
       [6.846295 ],
       [6.644738 ],
       [6.789981 ],
       [6.83955  ],
       [6.932483 ],
       [6.796056 ],
       [6.915972 ],
       [6.651462 ],
       [6.7934732],
       [6.780649 ],
       [6.9715166],
       [6.5264187],
       [6.6248813],
       [6.6983485],
       [6.773985 ],
       [6.6510944],
       [6.8238173],
       [6.841835 ],
       [6.8890305],
       [7.2227564],
       [7.0695887],
       [6.950442 ],
       [6.9312124],
       [6.934188 ],
       [6.7282343],
       [6.958731 ],
       [7.015548 ],
       [6.9961715],
       [6.598051 ],
       [6.765788 ],
       [6.7955785],
       [7.0446353],
       [6.6897945],
       [6.7603617],
       [6.8610744],
       [6.822654 ],
       [6.9522305],
       [6.640952 ],
       [6.8102937],
       [6.9184146],
       [6.884267 ],
       [6.9684505],
       [6.7822294],
       [6.752196 ],
       [6.6448374],
       [6.7071557],
       [6.7528653],
       [7.066042 ],
       [6.76864  ],
       [6.953511 ],
       [6.863411 ],
       [6.9894133],
       [6.7229066],
       [6.822093 ],
       [6.77349  ],
       [6.735635 ],
       [6.8459663],
       [6.98024  ],
       [6.868224 ],
       [6.7948027],
       [7.0633006],
       [7.0107546],
       [6.881767 ],
       [6.589208 ],
       [6.70796  ],
       [6.729792 ],
       [6.8298388],
       [6.780303 ],
       [6.7533283],
       [6.816014 ],
       [6.8410354],
       [6.8209453],
       [6.9341545],
       [6.8260956],
       [6.872464 ],
       [6.9008865],
       [6.6687145],
       [6.734255 ],
       [6.752778 ],
       [6.676468 ],
       [6.6208196],
       [6.826543 ],
       [6.8148823],
       [6.936204 ],
       [7.0006747],
       [6.659194 ],
       [6.8028617],
       [7.0066195],
       [6.8354187],
       [6.8413606],
       [7.078059 ],
       [6.854513 ],
       [6.913252 ],
       [6.7125406],
       [6.7112784],
       [6.7500663],
       [7.0494337],
       [6.741903 ],
       [6.959892 ],
       [6.8652043],
       [6.7314124],
       [6.941307 ],
       [6.824474 ],
       [6.781445 ],
       [6.8776855],
       [6.7609353],
       [6.8036685],
       [6.7777624],
       [7.0084076],
       [7.0053735],
       [6.8362184],
       [6.6855364],
       [6.782059 ],
       [6.906924 ],
       [6.8029385],
       [6.7551923],
       [6.9101167],
       [7.081464 ],
       [6.82483  ],
       [6.9456644],
       [6.8886614],
       [6.7129216],
       [6.9019284],
       [6.729088 ],
       [6.98008  ],
       [6.815116 ],
       [6.9120173],
       [6.7688036],
       [7.0330276],
       [7.0255136],
       [6.820474 ],
       [6.811937 ],
       [6.615718 ],
       [6.7750998],
       [6.821397 ],
       [6.7138424],
       [6.948425 ],
       [6.469279 ],
       [6.8761425],
       [6.9105487],
       [6.667435 ],
       [6.8281446],
       [6.735221 ],
       [6.7702312],
       [6.739975 ],
       [6.758831 ],
       [6.712591 ],
       [6.6185565],
       [6.927519 ],
       [6.73438  ],
       [6.7808685],
       [6.658591 ],
       [6.79281  ],
       [6.6462708],
       [6.80544  ],
       [6.566034 ],
       [6.8428993],
       [6.9618883],
       [6.7324543],
       [6.8088756],
       [6.838352 ],
       [6.7491484],
       [6.712629 ],
       [6.930092 ],
       [6.8753166],
       [6.782728 ],
       [6.7267694],
       [6.899567 ],
       [6.921564 ],
       [6.7556467],
       [6.867861 ],
       [6.777275 ],
       [6.8816204],
       [6.9350996],
       [6.6294007],
       [6.716633 ],
       [7.0269394],
       [6.977229 ],
       [6.955068 ],
       [6.8341937],
       [7.0309057],
       [6.7545996],
       [6.6754875],
       [6.872521 ],
       [6.851539 ],
       [6.886574 ],
       [6.7145195],
       [6.819415 ],
       [6.7506332],
       [6.7299814],
       [6.7144947],
       [6.6827703],
       [6.8323145],
       [6.8612666],
       [6.867172 ],
       [6.765219 ],
       [6.837509 ],
       [6.7606325],
       [6.746273 ],
       [6.9350033],
       [6.7996664],
       [6.7986884],
       [6.7518716],
       [6.913065 ],
       [6.8588567],
       [6.9186506],
       [7.081278 ],
       [6.9154086],
       [6.979892 ],
       [6.7019315],
       [6.839353 ],
       [6.7618527],
       [6.9591722],
       [6.6420164],
       [6.6431804],
       [6.7955556],
       [6.9193716],
       [6.4317718],
       [6.833623 ],
       [6.701023 ],
       [7.062759 ],
       [6.932583 ],
       [6.827131 ],
       [6.827897 ],
       [6.757407 ],
       [6.817527 ],
       [6.6077256],
       [6.9278116],
       [7.0288863],
       [6.9057355],
       [6.8837767],
       [6.7238708],
       [7.0108404],
       [6.759404 ],
       [6.7774525],
       [7.037156 ],
       [6.8422966],
       [6.763576 ],
       [6.9279785],
       [6.72762  ],
       [6.9601316],
       [6.9194927],
       [6.9352627],
       [6.6331587],
       [7.005666 ],
       [6.5589557],
       [6.844135 ],
       [6.805567 ],
       [6.6728826],
       [6.6440687],
       [6.86656  ],
       [6.907539 ],
       [6.7719316],
       [6.7349854],
       [6.8339643],
       [6.6689672],
       [6.898485 ],
       [6.614362 ],
       [6.60198  ],
       [6.803777 ],
       [6.8582077],
       [6.8121433],
       [6.7843513],
       [7.0712185],
       [6.9050436],
       [6.689269 ],
       [7.0624785],
       [7.062608 ],
       [6.886809 ],
       [6.767621 ],
       [7.0244975],
       [6.899411 ],
       [6.99271  ],
       [6.7463384],
       [6.562502 ],
       [6.716112 ],
       [6.8611817],
       [6.9982986],
       [6.705489 ],
       [6.804545 ],
       [6.9657216],
       [6.8498936],
       [6.8759723],
       [6.8610687],
       [6.9055557],
       [6.767131 ],
       [6.6706696],
       [7.038954 ],
       [6.7652235],
       [7.1497846],
       [6.845964 ],
       [6.8313575],
       [6.9110336],
       [6.802669 ],
       [6.8850303],
       [6.866838 ],
       [6.7143703],
       [6.7127743],
       [7.128704 ],
       [6.804127 ],
       [6.8846107],
       [6.783038 ],
       [6.7649126],
       [6.892523 ],
       [6.970704 ],
       [6.848866 ]], dtype=float32)

In [ ]:
y_pt=pd.DataFrame(y_pt,columns=['predicted_rating'])
y_pt

     predicted_rating
0            6.763661
1            6.820114
2            6.572635
3            6.634774
4            6.625891
..                ...
445          6.783038
446          6.764913
447          6.892523
448          6.970704
449          6.848866

[450 rows x 1 columns]

In [ ]:
df_actual_pt=pd.concat([df_pt,y_pt],axis=1)
df_actual_pt

,player_name,team,opponent_team,minutes_played,goals,assists,shots,passes_completed,tackles,rating,predicted_rating
0,Aaron Ramsdale,Arsenal,Chelsea,71.903226,0.193548,0.290323,2.838710,41.612903,2.000000,6.789032,6.763661
1,Aaron Ramsdale,Arsenal,Liverpool,76.086957,0.391304,0.043478,2.782609,47.369565,2.217391,6.848696,6.820114
2,Aaron Ramsdale,Arsenal,Manchester City,76.111111,0.111111,0.177778,2.644444,47.288889,1.977778,6.601333,6.572635
3,Aaron Ramsdale,Arsenal,Manchester United,73.000000,0.218750,0.156250,2.250000,46.093750,1.531250,6.668750,6.634774
4,Aaron Ramsdale,Arsenal,Tottenham,74.583333,0.194444,0.166667,2.250000,43.527778,1.833333,6.658333,6.625891
...,...,...,...,...,...,...,...,...,...,...,...
445,Yves Bissouma,Tottenham,Arsenal,77.935484,0.193548,0.290323,2.483871,48.838710,2.064516,6.783871,6.783038
446,Yves Bissouma,Tottenham,Chelsea,76.236842,0.236842,0.236842,2.131579,45.631579,1.868421,6.765000,6.764913
447,Yves Bissouma,Tottenham,Liverpool,75.857143,0.333333,0.214286,2.452381,46.642857,2.190476,6.896429,6.892523
448,Yves Bissouma,Tottenham,Manchester City,73.777778,0.422222,0.200000,2.244444,45.977778,2.066667,6.974000,6.970704
449,Yves Bissouma,Tottenham,Manchester United,74.882353,0.294118,0.264706,2.294118,46.176471,1.735294,6.858529,6.848866

In [ ]:
filtered_df = df_actual_pt[
    (df_actual_pt['team'].isin(['Arsenal','Manchester City'])) &
    (df_actual_pt['opponent_team'].isin(['Arsenal','Manchester City']))
].sort_values(by='predicted_rating', ascending=False)

filtered_df

,player_name,team,opponent_team,minutes_played,goals,assists,shots,passes_completed,tackles,rating,predicted_rating
122,Declan Rice,Arsenal,Manchester City,74.780000,0.640000,0.220000,2.640000,48.500000,2.080000,7.259800,7.271440
442,William Saliba,Arsenal,Manchester City,74.970588,0.529412,0.235294,2.500000,40.852941,1.911765,7.126176,7.128704
407,Takehiro Tomiyasu,Arsenal,Manchester City,76.461538,0.512821,0.179487,2.589744,45.948718,1.948718,7.077949,7.071218
240,Kyle Walker,Manchester City,Arsenal,74.939394,0.484848,0.242424,2.393939,46.424242,1.696970,7.073333,7.049434
170,Erling Haaland,Manchester City,Arsenal,74.684211,0.500000,0.157895,2.289474,46.236842,2.131579,7.037105,7.015548
205,Jeremy Doku,Manchester City,Arsenal,76.000000,0.487179,0.179487,2.256410,50.282051,1.692308,7.000256,7.010755
195,Jack Grealish,Manchester City,Arsenal,75.526316,0.368421,0.289474,2.421053,48.000000,2.236842,7.002632,6.989413
327,Oleksandr Zinchenko,Arsenal,Manchester City,75.390244,0.292683,0.243902,2.926829,42.975610,1.975610,6.878049,6.872521
235,Kevin De Bruyne,Manchester City,Arsenal,73.625000,0.281250,0.250000,2.500000,47.968750,2.343750,6.868437,6.854513
390,Ruben Dias,Manchester City,Arsenal,75.534884,0.302326,0.209302,2.325581,51.534884,2.279070,6.863488,6.844135
380,Rodri,Manchester City,Arsenal,73.484848,0.424242,0.060606,2.000000,44.424242,2.151515,6.853636,6.842297
232,Kai Havertz,Arsenal,Manchester City,74.153846,0.230769,0.282051,2.564103,50.538462,2.000000,6.831282,6.835419
67,Bukayo Saka,Arsenal,Manchester City,74.878788,0.272727,0.303030,2.606061,43.515152,1.424242,6.857576,6.834040
225,Julian Alvarez,Manchester City,Arsenal,75.642857,0.333333,0.142857,2.595238,47.809524,1.928571,6.836190,6.826543
215,John Stones,Manchester City,Arsenal,74.500000,0.238095,0.261905,2.428571,48.833333,2.357143,6.831190,6.820945
275,Manuel Akanji,Manchester City,Arsenal,77.694444,0.305556,0.166667,2.611111,47.805556,2.027778,6.828611,6.811937
182,Gabriel Martinelli,Arsenal,Manchester City,74.033333,0.333333,0.166667,1.966667,45.566667,1.800000,6.811333,6.810294
345,Phil Foden,Manchester City,Arsenal,72.575000,0.325000,0.100000,2.800000,47.225000,2.125000,6.811250,6.798688
152,Eddie Nketiah,Arsenal,Manchester City,74.482759,0.206897,0.310345,2.551724,43.068966,2.000000,6.810000,6.793473
247,Leandro Trossard,Arsenal,Manchester City,75.371429,0.285714,0.142857,2.542857,48.942857,2.314286,6.797714,6.781445
315,Nathan Ake,Manchester City,Arsenal,73.451613,0.193548,0.322581,2.677419,45.677419,1.677419,6.799032,6.777275
287,Martin Odegaard,Arsenal,Manchester City,71.387097,0.290323,0.193548,2.193548,44.838710,1.645161,6.784516,6.770231
177,Gabriel Jesus,Arsenal,Manchester City,75.534884,0.255814,0.186047,2.279070,47.953488,2.046512,6.767442,6.760362
222,Jorginho,Arsenal,Manchester City,74.250000,0.250000,0.166667,2.194444,49.083333,2.361111,6.759167,6.752778
52,Ben White,Arsenal,Manchester City,72.032258,0.225806,0.258065,2.387097,42.387097,1.677419,6.766129,6.751365
417,Thomas Partey,Arsenal,Manchester City,77.536585,0.219512,0.195122,2.317073,47.292683,2.439024,6.752927,6.746338
55,Bernardo Silva,Manchester City,Arsenal,71.343750,0.250000,0.156250,2.125000,45.250000,2.375000,6.740000,6.711148
295,Mateo Kovacic,Manchester City,Arsenal,73.404762,0.119048,0.285714,2.095238,47.833333,1.928571,6.668095,6.658591
2,Aaron Ramsdale,Arsenal,Manchester City,76.111111,0.111111,0.177778,2.644444,47.288889,1.977778,6.601333,6.572635
155,Ederson,Manchester City,Arsenal,76.590909,0.090909,0.136364,2.590909,44.477273,2.022727,6.538182,6.526419